export const NETWORK_STATUS_CONNECT = 'NETWORK_STATUS_CONNECT';
export const AUTH_SET_EMAIL = 'AUTH_SET_EMAIL';
export const AUTH_SET_PASSWORD = 'AUTH_SET_PASSWORD';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
